---
driver:
  name: terraform
  variable_files:
    - testing.tfvars

provisioner:
  name: terraform

platforms:
  - name: ubuntu
  
verifier:
  name: terraform
  systems:
    - name: default
      backend: ssh
      key_files: 
        - ~/.ssh/id_rsa
      hosts_output: public_dns
      user: ubuntu

suites:
  - name: default